//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogBookWPFApplication.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int DetaiID { get; set; }
        public int LearnerID { get; set; }
        public string Date { get; set; }
        public string TrainedIn { get; set; }
        public int MentorID { get; set; }
    
        public virtual AttendanceMaster AttendanceMaster { get; set; }
        public virtual Person Person { get; set; }
    }
}
